# -*- coding: utf-8 -*-
"""Restaurant_growth_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HjLLwNH6_elBzEeJyJvD9UMlJ_r1Hjk
"""

import pandas as pd

df = pd.read_csv("SkyCity.csv")

df.head()

df.columns

df.info()

df.isnull().sum()

df.describe()

df.sort_values("MonthlyOrders", ascending=False).head(10)

df["TotalRevenue"]=(df["InStoreRevenue"]+df["UberEatsRevenue"]+df["DoorDashRevenue"]+df["SelfDeliveryRevenue"])

df.sort_values("TotalRevenue", ascending=False).head(10)

df["TotalProfit"]=(df["InStoreNetProfit"]+df["UberEatsNetProfit"])

df.sort_values("TotalProfit", ascending=False).head(10)

import numpy as np

conditions = [(df["GrowthFactor"]>=80), (df["GrowthFactor"]>=50) & (df["GrowthFactor"]<80), (df["GrowthFactor"]<50)]

categories = ["High Growth", "Medium Growth", "Low Growth"]

df["GrowthCategory"]=np.select(conditions,categories,default="Low Growth")

df["GrowthCategory"].value_counts()

import matplotlib.pyplot as plt

df["GrowthCategory"].value_counts().plot(kind="bar")
plt.show()

plt.hist(df["TotalRevenue"])
plt.title("Revenue Distribution")
plt.xlabel("Revenue")
plt.ylabel("Number of restaurants")
plt.show()

plt.hist(df["MonthlyOrders"])
plt.title("Monthly Orders Distribution")
plt.xlabel("Orders")
plt.ylabel("Number of restaurants")
plt.show()

df.to_csv("Final_Restaurant_Analysis.csv",index=False)

import os
os.listdir()

